RCKit: DigitalSetter Class Reference
DigitalSetter Class Reference
Setter class that sets its value to an analog output pin.
#include <DigitalSetter.h>
Public Member Functions
DigitalSetter (uint8_t pin)
void setPin (uint8_t pin)
virtual void input (int value)
virtual void failsafe ()
Called when the source of input data is lost, and the Setter is required to fail in a safe way.
Detailed Description
Setter class that sets its value to an analog output pin.
Author:
Mike McCauley (mikem@open.com.au)
Examples:
DifferentialRCRx.pde, HBridge2RCRx.pde, HBridgeRCRx.pde, RCRxEthernet.pde, RCRxWiShield.pde, and TestSuite.pde.
Constructor & Destructor Documentation
DigitalSetter::DigitalSetter (uint8_t pin)
Parameters:
[in] pin The pin number of the digital output to set Caller is expected to have set it as an output already
Author:
Mike McCauley (mikem@open.com.au)
References setPin().
Member Function Documentation
void DigitalSetter::input (int value) [virtual]
Input the value to be used to set the analog output Digital outputs are 0 or 1 Inout 0 produces digital output of 0. All other values produce output of 1
Parameters:
[in] value The input 0 for off, all other values for on
Reimplemented from Setter.
Referenced by failsafe().
void DigitalSetter::setPin (uint8_t pin)
Set or change the output pin
Parameters:
[in] pin The Arduino pin to use for output
Referenced by DigitalSetter().
The documentation for this class was generated from the following files:
DigitalSetter.h
DigitalSetter.cpp