RCKit: SetterDebug Class Reference
SetterDebug Class Reference
Class for testing Setters. Used by the sample TestSuite sketch.
#include <SetterDebug.h>
Public Member Functions
virtual void input (int value)
int lastValue ()
virtual void failsafe ()
boolean failed ()
Public Member Functions inherited from Setter
Setter ()
Constructor.
Setter (Setter *target)
Constructor with setting the target.
virtual void setTarget (Setter *target)
void setFailsafeValue (int failsafeValue)
Sets the failsafeValue.
int failsafeValue ()
Additional Inherited Members
Protected Attributes inherited from Setter
Setter * _target
This is the instance of Setter that will be given the transfotmed output value.
int _failsafeValue
Detailed Description
Class for testing Setters. Used by the sample TestSuite sketch.
Author:
Mike McCauley (mikem.nosp@m.@ope.nosp@m.n.com.nosp@m..au)
Examples:
TestSuite.pde.
Member Function Documentation
boolean SetterDebug::failed ()
Returns whether there has been a failsafe event
Examples:
TestSuite.pde.
void SetterDebug::failsafe () virtual
Called when the source of input data is lost, and the Setter is required to fail in a safe way
Reimplemented from Setter.
References Setter::failsafeValue(), and input().
void SetterDebug::input (int value) virtual
Input the value to be inverted
Parameters:
[in] value The input value
Author:
Mike McCauley (mikem.nosp@m.@ope.nosp@m.n.com.nosp@m..au)
Reimplemented from Setter.
Referenced by failsafe().
int SetterDebug::lastValue ()
Return the last value that was set here
Examples:
TestSuite.pde.
The documentation for this class was generated from the following files:
SetterDebug.h
SetterDebug.cpp